### ISSUE TITLE
Create Wiki entry for each method

### ISSUE THREAD

**Issue by pjmaechling** [SCECcode/bbp#15]
Create a short wiki entry on describing principles used by each method. Enable wiki so that model developers can add material to their entries as needed.

**Comment by fabiolsilva** [comment]
For the 19.4.0 release, collected per-method documentation from each modeling group and included the provided pdf files in the doc directory. Available both at the Wiki and inside the distribution with commit 108b8b048dd2e5011e3c48770cdfa96216689f29
