### ISSUE TITLE
Wiki entry for multi-segment rupture

### ISSUE THREAD

**Issue by pjmaechling** [SCECcode/bbp#16]
Create a new wiki entry that describes how to use the new multi-segment capabilities of BBP.

**Comment by fabiolsilva** [comment]
Created a Utilities page that describes some of the multi-segment tools available with the BBP. Page copied from Wiki to main distribution with commit 108b8b048dd2e5011e3c48770cdfa96216689f29

Includes information on running stand alone and cluster multi-segment simulations.
