### ISSUE TITLE
metadata.txt not created

### ISSUE THREAD

**Issue by kevinmilner** [SCECcode/bbp#23]
The wiki page for "Running Simulations" states:

>Metadata capturing all the executable calls is located in `tmpdata/<simulation ID>/metadata.txt` for careful tracing of exactly what was called. Both the log files and metadata can be useful if troubleshooting an issue.

But this file isn't being created. No file named 'metadata.txt' is generated anywhere in the bbp_data file tree.

**Comment by fabiolsilva** [comment]
Fixed documentation to remove reference to metadata.txt file that is no longer generated by the BBP.
