### ISSUE TITLE
How to run the code with user-defined velocity model

### ISSUE THREAD

**Issue by Avazy** [SCECcode/bbp#27]
In the Broadband Platform, 1D velocity model are available for just  few regions. But I want to research other regions, can I use the user-defined velocity files? And how to set the file?

**Comment by fabiolsilva** [comment]
This is a question we often receive from users. Unfortunately, it is not possible for users to set up their own regions and 1D velocity models on the BBP. We updated the FAQ on the Wiki and the BBP documentation to address this issue.  We hope this is something that one day can potentially be added to a future version of the BBP.
