### ISSUE TITLE
geoutm() routine needs corrections

### ISSUE THREAD

**Issue by danielpeter** [SCECcode/bbp#37]
Please note that your geoutm() routine provided to convert long/lat to UTM coordinates contains two 2 mistakes:

source file: geo_utm.f

line 98:
https://github.com/SCECcode/bbp/blob/1e5fdb50df3e3d576584ec1bdf5339b1144da95d/bbp/src/gp/ModelCords/geo_utm.f#L98

wrong: `f3=15.d0*e4/256.d0*45.d0*e6/1024.d0`
correct would be: `f3=15.d0*e4/256.d0 + 45.d0*e6/1024.d0`

line 163
https://github.com/SCECcode/bbp/blob/1e5fdb50df3e3d576584ec1bdf5339b1144da95d/bbp/src/gp/ModelCords/geo_utm.f#L163

wrong: `f3=5.d0*3.d0*t1+10.d0*c1-4.d0*c1**2-9.d0*ep2`
correct would be: `f3=5.d0 + 3.d0*t1+10.d0*c1-4.d0*c1**2-9.d0*ep2`

the above corrections could be verified by looking at the original publication:
Snyder, J.P., Map projections - a working manual, USGS professional paper 1395, 1987
https://doi.org/10.3133/pp1395

line 98 mistake/correction: see page 61, eq. 3-21 for M
line 163 mistake/correction: see page 63, eq. 8-17 for phi

the above error will lead to a positional error of ~7 m when converting lon/lat to UTM.

best regards,
daniel

**Comment by fabiolsilva** [comment]
Thanks for bringing up this issue, it does appear like the implementation on the Broadband Platform should be corrected.

As per Rob Graves, selecting the option for UTM coordinates (which would call this routine) is not used in the typical GP implementation on the Broadband Platform, so the change shouldn’t have any impact on GP results.

But I think we should apply the suggested modifications to the routine to make it match the algorithm from the referenced publication.
