### ISSUE TITLE
An Installation problem

### ISSUE THREAD

**Issue by Chimon108** [SCECcode/bbp#45]
Hello, @[Fabio Silva](https://github.com/fabiolsilva). I have a stupid problem when I try to install the LA Basin region data. I followed the instruction and succeeded installing for the first time, but I couldn't download it again although I repeated the instruction and I got enough space. It showed the problem as follows when I ran `bash easy_install_bbp_19.4.0.sh`:

```
=> Installing Broadband Platform Velocity Model Packages
==> LA Basin
tar (child): labasin500-velocity-model-19.4.0.tar.gz：Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
md5sum: labasin500-velocity-model-19.4.0.tar.gz: No such file or directory

=> ERROR! MD5SUM check failed for labasin500-velocity-model-19.4.0.tar.gz
```

I use Ubuntu 20.04 with VMware Workstation. My software dependencies:
Python 2.7.14 :: Anaconda, Inc.
scipy (1.2.3)
matplotlib (2.2.3)
numpy (1.16.6)
pyproj (1.9.6)
FFTW library 3.3.10
tar (GNU tar) 1.30

I checked the https://hypocenter.usc.edu/research/bbp/versions/19.4.0/*** (in the `easy_install_bbp_19.4.0.sh`) and failed to enter the website, showing 502 error. Should I change something in `easy_install_bbp_19.4.0.sh` file to solve this problem? Thank you in advance for reviewing.

**Comment by MHZH123** [comment]
have you solved this issue?

**Comment by Haoger1** [comment]
Same issue! Have you addressed?
